### ISSUE TITLE
Issue with CSpect 2.16.0?

### ISSUE THREAD

**Issue by FranticOrange** [stefanbylund/zxnext_level9#1]
Hi - really appreciate the work you've done on this. However, when I'm trying to use the batch files to run each game, CSpect opens but just stays at a black screen. The normal boot up into NextZXOS works fine.

Is this something you're able to recreate or do you need more information?

Thanks.

**Comment by FranticOrange** [comment]
Actually, I just realised I needed to edit the .bat file to include the -sound switch as I don't use sound with CSpect. Feel free to close this, sorry for the inconvenience.

**Comment by stefanbylund** [comment]
I'm glad it worked out for you.

CSpect depends on [OpenAL](https://www.openal.org/) for generating sound. It could be that if you don't have OpenAL installed, CSpect will misbehave even though the executed program does not use any sound. As you've seen, the -sound option disables the sound support in CSpect and probably makes it not depend on OpenAL as well.
